name: mirror

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 11 * * *'

concurrency:
  group: github-mirror

jobs:
  mirror-yocto-meta-selinux:
    runs-on: ubuntu-latest
    name: yocto/meta-selinux
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: jhnc-oss/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: "${{ secrets.SSH_KNOWN_HOSTS }}"
        with:
          source-repo: "https://git.yoctoproject.org/git/meta-selinux.git"
          destination-repo: "git@github.com:jhnc-oss/meta-selinux.git"