name: mirror

on:
  push:
  pull_request:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: github-mirror

jobs:
  mirror-repos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mirror_config:
          - {
              src_repo: "https://github.com/kraj/meta-clang.git",
              dest_repo: "meta-clang",
              key_id: "META_CLANG",
            }
          - {
              src_repo: "https://github.com/openembedded/openembedded-core.git",
              dest_repo: "openembedded-core",
              key_id: "OPENEMBEDDED",
            }
          - {
              src_repo: "https://github.com/openembedded/meta-openembedded.git",
              dest_repo: "meta-openembedded",
              key_id: "META_OPENEMBEDDED",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-mingw.git",
              dest_repo: "meta-mingw",
              key_id: "META_MINGW",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-selinux.git",
              dest_repo: "meta-selinux",
              key_id: "META_SELINUX",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/poky.git",
              dest_repo: "poky",
              key_id: "POKY",
            }
          - {
              src_repo: "https://github.com/vmware/vsphere-automation-sdk-python.git",
              dest_repo: "vsphere-automation-sdk-python",
              key_id: "VSPHERE_AUTOMATION_SDK_PYTHON",
            }
          - {
              src_repo: "https://github.com/awulkiew/graphical-debugging-vscode",
              dest_repo: "graphical-debugging-vscode",
              key_id: "GRAPHICAL_DEBUGGING_VSCODE",
            }
          - {
              src_repo: "https://github.com/mneuroth/SciTEQt",
              dest_repo: "SciTEQt",
              key_id: "SCITEQT",
            }
          - {
              src_repo: "https://github.com/parkouss/funq.git",
              dest_repo: "funq",
              key_id: "FUNQ",
            }
          - {
              src_repo: "https://github.com/FreeOpcUa/python-opcua.git",
              dest_repo: "python-opcua",
              key_id: "PYTHON_OPCUA",
            }
          - {
              src_repo: "https://github.com/danmar/cppcheck",
              dest_repo: "cppcheck",
              key_id: "CPPCHECK",
            }
          - {
              src_repo: "https://github.com/meta-rust/meta-rust",
              dest_repo: "meta-rust",
              key_id: "META_RUST",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-raspberrypi.git",
              dest_repo: "meta-raspberrypi",
              key_id: "META_RASPBERRYPI",
            }
          - {
              src_repo: "https://github.com/FreeOpcUa/opcua-asyncio.git",
              dest_repo: "opcua-asyncio",
              key_id: "OPCUA_ASYNCIO",
            }
          - {
              src_repo: "https://sourceware.org/git/glibc.git",
              dest_repo: "glibc",
              key_id: "GLIBC",
            }
          - {
              src_repo: "https://github.com/msys2/MINGW-packages.git",
              dest_repo: "MINGW-packages",
              key_id: "MINGW_PACKAGES",
            }
          - {
              src_repo: "https://gitlab.freedesktop.org/NetworkManager/NetworkManager.git",
              dest_repo: "NetworkManager",
              key_id: "NETWORKMANAGER",
            }
          - {
              src_repo: "https://gitlab.gnome.org/GNOME/network-manager-applet.git",
              dest_repo: "network-manager-applet",
              key_id: "NETWORK_MANAGER_APPLET",
            }
          - {
              src_repo: "https://gitlab.freedesktop.org/plymouth/plymouth",
              dest_repo: "plymouth",
              key_id: "PLYMOUTH",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-intel.git",
              dest_repo: "meta-intel",
              key_id: "META_INTEL",
            }
          - {
              src_repo: "https://github.com/conan-io/meta-conan.git",
              dest_repo: "meta-conan",
              key_id: "META_CONAN",
            }
          - {
              src_repo: "https://github.com/Freescale/meta-freescale-distro.git",
              dest_repo: "meta-freescale-distro",
              key_id: "META_FREESCALE_DISTRO",
            }
          - {
              src_repo: "https://github.com/Freescale/meta-freescale.git",
              dest_repo: "meta-freescale",
              key_id: "META_FREESCALE",
            }
          - {
              src_repo: "https://github.com/rust-lang/crates.io-index.git",
              dest_repo: "crates.io-index",
              key_id: "CRATESIO_INDEX",
            }
          - {
              src_repo: "https://invent.kde.org/packaging/yocto-meta-kf5.git",
              dest_repo: "yocto-meta-kf5",
              key_id: "YOCTO_META_KF5",
            }
          - {
              src_repo: "https://github.com/KDE/yocto-meta-kf6.git",
              dest_repo: "yocto-meta-kf6",
              key_id: "YOCTO_META_KF6",
            }
          - {
              src_repo: "https://github.com/mneuroth/QuickScintilla.git",
              dest_repo: "QuickScintilla",
              key_id: "QUICKSCINTILLA",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-security.git",
              dest_repo: "meta-security",
              key_id: "META_SECURITY",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/yocto-kernel-cache.git",
              dest_repo: "yocto-kernel-cache",
              key_id: "YOCTO_KERNEL_CACHE",
            }
          - {
              src_repo: "https://github.com/nxp-imx/meta-imx.git",
              dest_repo: "meta-imx",
              key_id: "META_IMX",
            }
          - {
              src_repo: "https://github.com/nxp-imx-support/meta-nxp-demo-experience.git",
              dest_repo: "meta-nxp-demo-experience",
              key_id: "META_NXP_DEMO_EXPERIENCE",
            }
          - {
              src_repo: "https://code.qt.io/yocto/meta-qt6.git",
              dest_repo: "meta-qt6",
              key_id: "META_QT6",
            }
          - {
              src_repo: "https://github.com/Freescale/meta-freescale-3rdparty.git",
              dest_repo: "meta-freescale-3rdparty",
              key_id: "META_FREESCALE_3RDPARTY",
            }
          - {
              src_repo: "https://github.com/PowerShell/openssh-portable.git",
              dest_repo: "openssh-portable",
              key_id: "OPENSSH_PORTABLE",
            }
          - {
              src_repo: "https://github.com/KDE/networkmanager-qt.git",
              dest_repo: "networkmanager-qt",
              key_id: "NETWORKMANAGER_QT",
            }
          - {
              src_repo: "https://github.com/intel/linux-intel-lts.git",
              dest_repo: "linux-intel-lts",
              key_id: "LINUX_INTEL_LTS",
            }
          - {
              src_repo: "https://github.com/rustsec/advisory-db.git",
              dest_repo: "advisory-db",
              key_id: "ADVISORY_DB",
            }
          - {
              src_repo: "https://git.yoctoproject.org/meta-virtualization",
              dest_repo: "meta-virtualization",
              key_id: "META_VIRTUALIZATION",
            }
          - {
              src_repo: "https://github.com/OSSystems/meta-browser.git",
              dest_repo: "meta-browser",
              key_id: "META_BROWSER",
            }
          - {
              src_repo: "https://github.com/ashie/meta-inputmethod.git",
              dest_repo: "meta-inputmethod",
              key_id: "META_INPUTMETHOD",
            }
          - {
              src_repo: "https://codeberg.org/flk/meta-wayland.git",
              dest_repo: "meta-wayland",
              key_id: "META_wayland",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-arm.git",
              dest_repo: "meta-arm",
              key_id: "META_ARM",
            }
          - {
              src_repo: "https://github.com/CVEProject/cvelistV5.git",
              dest_repo: "cvelistV5",
              key_id: "CVELISTV5",
            }
          - {
              src_repo: "https://gitlab.com/syslinbit/public/yocto-vex-check.git",
              dest_repo: "yocto-vex-check",
              key_id: "YOCTO_VEX_CHECK",
            }
          - {
              src_repo: "https://github.com/nxp-imx/uboot-imx.git",
              dest_repo: "uboot-imx",
              key_id: "UBOOT_IMX",
            }

    name: ${{ matrix.mirror_config.dest_repo }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets[format('SSH_PRIVATE_KEY_{0}', matrix.mirror_config.key_id)] }}
          SSH_KNOWN_HOSTS: "${{ secrets.SSH_KNOWN_HOSTS }}"
        with:
          source-repo: ${{ matrix.mirror_config.src_repo }}
          destination-repo: "git@github.com:jhnc-oss/${{ matrix.mirror_config.dest_repo }}.git"
          dry-run: ${{ github.ref != 'refs/heads/main' }}
