name: mirror

on:
  push:
  pull_request:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: github-mirror

jobs:
  mirror-repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mirror_config:
          - {
              src_repo: "https://github.com/kraj/meta-clang.git",
              dest_repo: "meta-clang",
              key_id: "META_CLANG",
            }
          - {
              src_repo: "https://github.com/openembedded/openembedded-core.git",
              dest_repo: "openembedded-core",
              key_id: "OPENEMBEDDED",
            }
          - {
              src_repo: "https://github.com/openembedded/meta-openembedded.git",
              dest_repo: "meta-openembedded",
              key_id: "META_OPENEMBEDDED",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-mingw.git",
              dest_repo: "meta-mingw",
              key_id: "META_MINGW",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/meta-selinux.git",
              dest_repo: "meta-selinux",
              key_id: "META_SELINUX",
            }
          - {
              src_repo: "https://git.yoctoproject.org/git/poky.git",
              dest_repo: "poky",
              key_id: "POKY",
            }
          - {
              src_repo: "https://git.openembedded.org/meta-python2",
              dest_repo: "meta-python2",
              key_id: "META_PYTHON2",
            }
          - {
              src_repo: "https://github.com/vmware/vsphere-automation-sdk-python.git",
              dest_repo: "vsphere-automation-sdk-python",
              key_id: "VSPHERE_AUTOMATION_SDK_PYTHON",
            }
          - {
              src_repo: "https://github.com/awulkiew/graphical-debugging-vscode",
              dest_repo: "graphical-debugging-vscode",
              key_id: "GRAPHICAL_DEBUGGING_VSCODE",
            }
    name: ${{ matrix.mirror_config.dest_repo }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets[format('SSH_PRIVATE_KEY_{0}', matrix.mirror_config.key_id)] }}
          SSH_KNOWN_HOSTS: "${{ secrets.SSH_KNOWN_HOSTS }}"
        with:
          source-repo: ${{ matrix.mirror_config.src_repo }}
          destination-repo: "git@github.com:jhnc-oss/${{ matrix.mirror_config.dest_repo }}.git"
          dry-run: ${{ github.ref != 'refs/heads/main' }}
